Traceback (most recent call last):
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\henni\anaconda3\envs\j_books\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\henni\anaconda3\envs\j_books\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorboard.plugins.hparams import api as hp
from tensorflow import keras


from keras import layers
import keras_tuner as kt
from keras.preprocessing.image import ImageDataGenerator, img_to_array,load_img
from PIL import Image

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import os
import shap
import cv2

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mtensorflow[39;00m [38;5;28;01mas[39;00m [38;5;21;01mtf[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mtensorflow_datasets[39;00m [38;5;28;01mas[39;00m [38;5;21;01mtfds[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtensorboard[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplugins[39;00m[38;5;21;01m.[39;00m[38;5;21;01mhparams[39;00m [38;5;28;01mimport[39;00m api [38;5;28;01mas[39;00m hp

[1;31mModuleNotFoundError[0m: No module named 'tensorflow'
ModuleNotFoundError: No module named 'tensorflow'

